name = "kaczogrod smp modowany"
author = "Ferb2004"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd6e9eefcdcccce5acb54853dfb4534972b081bd9d158ce7544d807ede6a6670"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"

[options]
acceptable-game-versions = []
