name = "kaczogrod smp modowany"
author = "Ferb2004"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3df6b74531cd85d93e5da14c3ac4d35b1168763ede278b0c02925050a005551a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"

[options]
acceptable-game-versions = []
